version: '3'
services:
  db:
    image: bitnami/mysql:latest
    environment:
      - MYSQL_DATABASE=indexer
      - MYSQL_ROOT_USER=paipa
      - MYSQL_ROOT_PASSWORD=paipa
    volumes:
      - ./data:/var/lib/mysql
    ports:
        - "3306:3306"
